[tools]
neovim = "0.11.0"
starship = "1.19.0"
ghq = "1.6.1"
fzf = "0.53.0"
chezmoi = "2.50.0"
k9s = "0.40.10"
helm = "3.15.2"
helmfile = "0.166.0"
node = "22.4.0"
rust = "1.79.0"
kubectl = "1.30.2"
age = "1.1.1"
sops = "3.9.0"
ripgrep = "14.1.0"
cloudflared = "2024.6.1"
python = "3.12.4"
fd = "10.1.0"
hugo = "0.134.1"
go = "1.25.3"
redis = "7.4.1"
kubent = "0.7.3"
kubectx = "0.9.5"
pluto = "5.21.1"
zig = "0.13.0"
lima = "1.0.6"
yq = "4.45.1"
stern = "latest"
lazygit = "latest"
uv = "latest"
k6 = "latest"
krew = "0.4.5"
flux2 = "2.6.3"
gh = "latest"
